# config 配置

spring:
  application:
    name: frame-config
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XGLLHZ/springcloud-frame.git
          search-paths: frame-config/config
          username: XGLLHZ
          password: GHghpp19961003
        default-label: master

server:
  port: 8083
  servlet:
    context-path: /api
  tomcat:
    connection-timeout: 5000

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

